### ISSUE TITLE
breaking changes in 1.5

### ISSUE THREAD

**Issue by unional** [gliviu/dir-compare#12]
Hi, I notice there are some breaking behavior changes when upgrading from 1.4 to 1.5:

- the diff paths are changed from relative to absolute path
- the `compare()` function will throw instead of returning a rejected promise when the input path does not exist.

Are these intentional?
Especially the second one, my guess is that it is a regression.

Thanks for this very useful library thou. 🌷

**Comment by gliviu** [comment]
Yes, it is a regression added in https://github.com/gliviu/dir-compare/commit/635d0e084d99dc863ed0b601a40e2bf60ec96687.

> the compare() function will throw instead of returning a rejected promise when the input path does not exist.

Should be fixed in v1.5.3

> the diff paths are changed from relative to absolute path

Can you please explain how this affects your library. I attached a test project where relative dirs seem to work properly.

[test.zip](https://github.com/gliviu/dir-compare/files/2708857/test.zip)

**Comment by unional** [comment]
Thanks!

For the relative path, the change is relatively minor.

I was using it to display the changed files and expecting relative paths. So the test breaks. I can fix it by doing `path.relative(process.cwd(), diff.path1)`.

But that feels extra and could be fragile (to mitigate that, one way is to require the application to pass down `cwd`).

**Comment by gliviu** [comment]
Now I figure it is a mater of reporting the result. No need to change your code. I'll provide a fix soon.
