### ISSUE TITLE
Report different destination of symlinks

### ISSUE THREAD

**Issue by szpak** [gliviu/dir-compare#19]
#16 inspired me to make a test of the following case:

```
$ tree -C /tmp/22 /tmp/11
/tmp/22
├── 1
├── 2
└── 3 -> 2
/tmp/11
├── 1
├── 2
└── 3 -> 1

6 directories, 0 files
```

dir-compare reported that everything is fine:
```
$ dircompare.js -c -lrd /tmp/11/ /tmp/22
Entries are identical
total: 0, equal: 0, distinct: 0, only left: 0, only right: 0
```

It's usually not a big deal, however, on the way of a potential implementation of #16 it might be worth to add a check if a synlink points to the same place (both relative and absolute). I don't know how it is implemented in the current version, but I think that dir-compare shouldn't follow the link - just check if a destination is the same.

**Comment by szpak** [comment]
It's a little bit wider. dir-compare also doesn't detect that file in one directory is a symlink, which in the second is a subdirectory. Similarly, dir-compare could make clearly report if a file is a directory on the other side:

```
$ ll /tmp/22 /tmp/11                                                                                    10:05
/tmp/11:
total 0
drwx------. 2 foobar foobar 40 Dec 17 10:02 1/
lrwxrwxrwx. 1 foobar foobar  1 Dec 17 10:03 3 -> 1/

/tmp/22:
total 0
-rw-------. 1 foobar foobar  0 Dec 17 10:02 1
drwx------. 2 foobar foobar 40 Dec 17 10:03 3/
```

```
$ dircompare.js -c -lrd /tmp/11/ /tmp/22
[/] missing<-1
Entries are different
total: 1, equal: 0, distinct: 0, only left: 0, only right: 1
```

**Comment by gliviu** [comment]
> dir-compare reported that everything is fine

I'm not able to reproduce the issue. I attached my test case. Here is what I get.
```
tar -xvf 17.tar

dircompare a b
Entries are different
total: 3, equal: 2, distinct: 1, only left: 0, only right: 0

dircompare -c a b
Entries are different
total: 3, equal: 2, distinct: 1, only left: 0, only right: 0
```
Maybe your 1, 2, 3 files are identical as content, in which case, `dircompare` will not detect any difference.

This is because `dircompare` works on resolved links (if it can resolve them; see #16). In other words, it doesn't care how a link is resolved. It just compares the resolved file by size or by content.

To detect such cases, and not break existing rules, we would need another option. Something like `--compare-symlinks`.

This new option will be applied in addition to the other 'compare' options: `--compare-content`, `--compare-date`. So all combined comparison criteria must match in order to consider two entries identical.

By default the new option will be disabled, not to break existing behaviour.

**Comment by szpak** [comment]
That might be the case. On the left there was a symlink to a directory, on the right a directory itself (different, but still a directory).

I like the idea with the new option. If activated it could detect that there is a link and a directory. I'm not sure if the compared directories should be reported if there is a symlink on the one side and a directory on the other.

**Comment by gliviu** [comment]
I think it should report them as distinct. Just as it does if it finds a file and a directory with the same name.
```
# symlink on the left, dir on the right
[/] A6->missing(symlink directory)
[/] missing->A6(directory)
Entries are different
total: 2, equal: 0, distinct: 0, only left: 1, only right: 1

# both symlinks with the same name but pointing to different paths
[/] A6<>A6(symlink directory)
Entries are different
total: 1, equal: 0, distinct: 1, only left: 0, only right: 0

```
