### ISSUE TITLE
Line based comparator ignoreLineEnding problem

### ISSUE THREAD

**Issue by pgigler01** [gliviu/dir-compare#21]
Line based comparator ignoreLineEnding doesn't work correctly, when the files to be compared are bigger, than the BUF_SIZE (100000). In that case two files, which are only differs in line endings, such as one has CRLF and the other has LF, are deemed to be different by the algorithm.

**Comment by gliviu** [comment]
Happens because the two buffers are simultaneously loaded with data. This causes them to get de-synchronized as differences between LF and CRLF files accumulates (each CRLF line has one more byte).
I'll have to rethink the algorithm and use independent buffer loading per left and right files.
Until then the obvious solution is to increase the buffer size beyond the largest compared file.
