### ISSUE TITLE
compareNameHandler doesn't run on all the files combinations 

### ISSUE THREAD

**Issue by moshfeu** [gliviu/dir-compare#25]
Consider the following structure

<img width="279" alt="Screen Shot 2020-11-24 at 1 11 02" src="https://user-images.githubusercontent.com/3723951/100025689-f1153800-2df1-11eb-846c-fb0eda55459a.png">

The library never compare _index.t_ and _index.cc_. The thing is that I want to ignore the extensions only for pair of extensions. In this example, I want the library to treat _index.t_ and _index.cc_ as the same file by the following code:

```ts
if (
  // options.ignoreExtension is ["t", "cc"]
  options.ignoreExtension.some((exts: [string, string]) => {
    return exts.includes(extnameOnly(name1)) && exts.includes(extnameOnly(name2));
  })
) {
  name1 = path.basename(name1, path.extname(name1));
  name2 = path.basename(name2, path.extname(name2));
}
```

https://github.com/moshfeu/vscode-compare-folders/pull/58/files#diff-b3ec7b5233f0b1a6113fd044710718c983a78f50e5960ddb0c0507fc9738e0dcR15

Test repo: https://github.com/moshfeu/dir-compare-test

**Comment by gliviu** [comment]
To properly solve it you have to somehow isolate the files corresponding to the extension pair so that `index.t` and `index.cc` are compared together. Supposing we only have one pair here is a [solution](https://github.com/moshfeu/dir-compare-test/commit/e6daf044bf22c09cc25f1b19fd28f8e5e0a0421d#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346).

We basically transform 
| Folder1  | Folder2  |
|----------|----------|
| index.a  | index.a  |
| index.h  | index.cc |
| index.tt | index.h  |
| index.z  | index.z  |

Into
| Folder1  | Folder2  |
|----------|----------|
| index.a  | index.a  |
| index.h  | index |
| index | index.h  |
| index.z  | index.z  |

After [sorting](https://github.com/gliviu/dir-compare/blob/master/src/entry/entryBuilder.js#L28) them we get
| Folder1  | Folder2  |
|----------|----------|
| index  | index |
| index.a  | index.a  |
| index.h | index.h  |
| index.z  | index.z  |

Now all files in extension pair are grouped at the top of the list and will be compared together.

This works well for one extension pair. If we have multiple pairs we should probably try to somehow group by each extension pair so that the file from first pair gets to the top, the file from second pair will go next and so on.
Maybe instead of cutting the extension we can assign some unique name for each extension pair.
For example lets assume `ignoreExtension: [['t', 'cc'], ['htm', 'html']]`.
We can say that `['t', 'cc']` => `ext1` and `['htm', 'html']` => `ext2`.
Thus we will transform
| Folder1  | Folder2  |
|----------|----------|
| index.a  | index.a  |
| index.html  | index.cc |
| index.tt | index.htm  |
| index.z  | index.z  |

Into
| Folder1  | Folder2  |
|----------|----------|
| index.a  | index.a  |
| index.ext2  | index.ext1 |
| index.ext1 | index.ext2  |
| index.z  | index.z  |

Which will get sorted into
| Folder1  | Folder2  |
|----------|----------|
| index.a  | index.a  |
| index.ext1  | index.ext1 |
| index.ext2 | index.ext2  |
| index.z  | index.z  |

I haven't tried but it could work.

**Comment by moshfeu** [comment]
I think I followed your idea and ended up with

https://github.com/moshfeu/vscode-compare-folders/pull/58/commits/29e235f8c1d5c1473d6265665dd91a5280afc253

What do you think?

**Comment by gliviu** [comment]
See my comments in commit.
