### ISSUE TITLE
compareDate milliseconds / seconds

### ISSUE THREAD

**Issue by pckhib** [gliviu/dir-compare#6]
[compareSync:119](https://github.com/gliviu/dir-compare/blob/master/compareSync.js#L119) and [compareAsync:147](https://github.com/gliviu/dir-compare/blob/master/compareAsync.js#L147)

I'm having a problem with the compareDate option on Windows.
If I copy a file and preserve the timestamp by copying the modification date with `utimesSync`, it only copies the seconds, not the milliseconds.
The `compareDate` functionality is using `getTime()` which returns milliseconds.

E.g. I have two files with two timestamps `1480843824000` and `1480843824030` in which I copied the mtime of the second to the first one. The seconds are the same, but the milliseconds are not, as they are not copied. So compareDate will always return false.

Maybe you could add an option to compare seconds and use `getTime() / 1000` to compare the date.

**Comment by gliviu** [comment]
What if I add some kind of 'date precision' option limited to [year, month, day, hour, minute, second].
If this option is not specified, the precision will default to milliseconds.

**Comment by pckhib** [comment]
That sounds good to me.

**Comment by gliviu** [comment]
Just noticed that node v0.10.29 stats.mtime has second precision on linux. Though it works with milliseconds in later versions.

**Comment by gliviu** [comment]
I see that most file systems have precision less than millisecond, worst being vfat with 2 seconds. Maybe we should have the default to ignore milliseconds when comparing dates.
This would solve your problem without any extra option.
Also instead of having a date rounding option I think it is more common sense to just use a tollerance value in seconds. For example when this option is set to 3 it will allow two files that differ by at most 3 seconds to be considered identical.
This option would be set by default to 1 covering most cases except for vfat where it needs to be used explicitly.
